FROM node:18.13-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN apk add python3 make g++
RUN npm install
COPY . .
EXPOSE 3000
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
ARG PORT
ENV PORT $PORT
ARG MAX_FILE_SIZE
ENV MAX_FILE_SIZE $MAX_FILE_SIZE
ARG DATASET_PATH
ENV DATASET_PATH $DATASET_PATH
ARG MEDIA_PATH
ENV MEDIA_PATH $MEDIA_PATH
ARG PUBLIC_MEDIA_PATH
ENV PUBLIC_MEDIA_PATH $PUBLIC_MEDIA_PATH
ARG CERTS_PATH
ENV CERTS_PATH $CERTS_PATH
ARG CONNECTION_PROFILE_PATH
ENV CONNECTION_PROFILE_PATH $CONNECTION_PROFILE_PATH
ARG WALLET_PATH
ENV WALLET_PATH $WALLET_PATH
ARG WEB_URL
ENV WEB_URL $WEB_URL
ARG WEB_NAME
ENV WEB_NAME $WEB_NAME
ARG CRON_INTERVAL_MIN
ENV CRON_INTERVAL_MIN $CRON_INTERVAL_MIN
ARG CRON_TIME_ZONE
ENV CRON_TIME_ZONE $CRON_TIME_ZONE
ARG MAIL_SERVICE
ENV MAIL_SERVICE $MAIL_SERVICE
ARG MAIL_HOST
ENV MAIL_HOST $MAIL_HOST
ARG MAIL_PORT
ENV MAIL_PORT $MAIL_PORT
ARG MAIL_USER
ENV MAIL_USER $MAIL_USER
ARG MAIL_PASS
ENV MAIL_PASS $MAIL_PASS
ARG MAIL_FROM
ENV MAIL_FROM $MAIL_FROM
ARG MAIL_TEMPLATE_PATH
ENV MAIL_TEMPLATE_PATH $MAIL_TEMPLATE_PATH
ARG MAIL_CONTACT
ENV MAIL_CONTACT $MAIL_CONTACT
ARG VERIFICATION_EXPIRES_HOURS
ENV VERIFICATION_EXPIRES_HOURS $VERIFICATION_EXPIRES_HOURS
ARG SSO_CLIENT_ID
ENV SSO_CLIENT_ID $SSO_CLIENT_ID
ARG SSO_CLIENT_SECRET
ENV SSO_CLIENT_SECRET $SSO_CLIENT_SECRET
ARG SSO_SCOPE
ENV SSO_SCOPE $SSO_SCOPE
ARG SSO_REDIRECT_URL
ENV SSO_REDIRECT_URL $SSO_REDIRECT_URL
ARG SSO_AUTH_URL
ENV SSO_AUTH_URL $SSO_AUTH_URL
ARG SSO_TOKEN_URL
ENV SSO_TOKEN_URL $SSO_TOKEN_URL
ARG SSO_API_TOKEN_EXP
ENV SSO_API_TOKEN_EXP $SSO_API_TOKEN_EXP
ARG OAUTH_TOKEN_SECRET
ENV OAUTH_TOKEN_SECRET $OAUTH_TOKEN_SECRET
ARG POSTGRES_HOST
ENV POSTGRES_HOST $POSTGRES_HOST
ARG POSTGRES_PORT
ENV POSTGRES_PORT $POSTGRES_PORT
ARG POSTGRES_DB
ENV POSTGRES_DB $POSTGRES_DB
ARG POSTGRES_USER
ENV POSTGRES_USER $POSTGRES_USER
ARG POSTGRES_PASS
ENV POSTGRES_PASS $POSTGRES_PASS
ARG POSTGRES_FORCE
ENV POSTGRES_FORCE $POSTGRES_FORCE
ARG POSTGRES_INIT
ENV POSTGRES_INIT $POSTGRES_INIT
ARG SESSION_CLEANUP_INTERVAL
ENV SESSION_CLEANUP_INTERVAL $SESSION_CLEANUP_INTERVAL
ARG SESSION_EXPIRES
ENV SESSION_EXPIRES $SESSION_EXPIRES
ARG SESSION_NAME
ENV SESSION_NAME $SESSION_NAME
ARG SESSION_SECRET
ENV SESSION_SECRET $SESSION_SECRET
ARG SESSION_MAX_AGE
ENV SESSION_MAX_AGE $SESSION_MAX_AGE
ARG FABRIC_CHANNEL_NAME
ENV FABRIC_CHANNEL_NAME $FABRIC_CHANNEL_NAME
ARG FABRIC_CHAINCODE_NAME
ENV FABRIC_CHAINCODE_NAME $FABRIC_CHAINCODE_NAME
ARG FABRIC_DEFAULT_ORG
ENV FABRIC_DEFAULT_ORG $FABRIC_DEFAULT_ORG
CMD ["npm", "start"]
